# Generated by Django 3.1.7 on 2021-03-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('courier_type', models.CharField(max_length=4)),
                ('rating', models.FloatField(default=5)),
                ('earnings', models.FloatField(default=0)),
                ('last_deliver_time', models.DateTimeField(null=True)),
                ('intervals', models.ManyToManyField(related_name='couriers', to='utils.Interval')),
                ('regions', models.ManyToManyField(related_name='couriers', to='utils.Region')),
            ],
        ),
    ]
