version: "3.8"

services:
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: 
      - .candyapi.env
  backend:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./candyapi:/usr/src/candyapi/candyapi
    environment:
      DJANGO_DATABASE_HOST: db
    env_file:
      - .candyapi.env
    depends_on:
      - db
    ports: 
      - 8000:8000

volumes:
  postgres_data:
