# Generated by Django 3.1.7 on 2021-03-17 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delievery',
            name='last_delievery_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 10, 39, 47, 918706, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
