# Generated by Django 3.1.7 on 2021-03-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delievery',
            name='transport_type',
            field=models.CharField(default='foot', max_length=4),
        ),
    ]
